### ISSUE TITLE
Icons and Favs

### ISSUE THREAD

**Issue by koolamusic** [wecodeafrica/hospitalsghana#2]
sizes="57x57" 
sizes="60x60" 
sizes="72x72" 
sizes="76x76" 
sizes="114x114"
sizes="120x120"
sizes="144x144"
sizes="152x152"
sizes="180x180"
sizes="192x192"
sizes="32x32" 
sizes="96x96" 
sizes="16x16"

**Comment by koolamusic** [comment]
We need and Icon and logo for the project using the above specs

**Comment by koolamusic** [comment]
@audreymengue there doesn't seem to be any PR here

**Comment by audreymengue** [comment]
so there is no pull request at all?
